version: 2
jobs:
  build:
    working_directory: /go/src/github.com/blend/go-sdk
    docker:
    - image: circleci/golang:1.12
    - image: circleci/postgres:9.6.2-alpine
      environment:
        POSTGRES_USER: circleci
        POSTGRES_DB: circleci
    steps:
    - checkout
    - run:
        name: new-install
        command: make new-install
    - run:
        name: ci
        command: make ci
    - run:
        name: codecov
        command: bash <(curl -s https://codecov.io/bash) -X fix -f coverage.txt
    - store_artifacts:
        path: coverage.html
        destination: coverage.html
workflows:
  version: 2
  build:
    jobs:
    - build
