#
# Copyright (c) 2022 - Present. Blend Labs, Inc. All rights reserved
# Use of this source code is governed by a MIT license that can be found in the LICENSE file.
#
#
# Copyright (c) 2021 - Present. Blend Labs, Inc. All rights reserved
# Blend Confidential - Restricted
#
target: "http://localhost:8080"
env: "local"