---
name: "Release Binaries"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:

  release_binaries:
    name: "Release Binaries"
    runs-on: ubuntu-latest  

    env:
      GO111MODULE: "on"
      CGO_ENABLED: "0"

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go 1.16.x
      uses: actions/setup-go@main
      with:
        go-version: ^1.16
      id: go

    - name: Install goreleaser
      run: go install github.com/goreleaser/goreleaser@latest

    - name: CI
      run: make release-binaries
